<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.props" />

  <PropertyGroup>
    <!-- target frameworks -->
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>

    <!-- Root Namespace -->
    <RootNamespace>PPWCode.Server.Core.Hangfire</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <!-- PPWCode -->
    <PackageReference Include="PPWCode.Server.Core" />
    <!-- Hangfire -->
    <PackageReference Include="Hangfire.Core" />
  </ItemGroup>

</Project>